source 'https://rubygems.org'

gem 'dotenv-rails', groups: [:development, :test]
gem 'rails', '~> 5.2'
gem 'sqlite3'
gem 'hcaptcha', require: 'hcaptcha/rails', path: '../..'

group :development do
  gem 'listen'
  gem 'byebug'
end
